version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    ports:
      - '8000:80'
    volumes:
      - '~/gitlab/config:/etc/gitlab'
      - '~/gitlab/logs:/var/log/gitlab'
      - '~/gitlab/data:/var/opt/gitlab'
    # links:
    #   - gitlab-runner
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: runner
    restart: always
    volumes:
      - '~/gitlab/gitlab-runner/config.toml:/etc/gitlab-runner/config.toml'
    # links:
    #   - gitlab

